/*
 * generated by Xtext
 */
package org.iworkz.qon;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class QonDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.iworkz.qon.ui.internal.QonDslActivator.getInstance().getInjector("org.iworkz.qon.QonDsl");
	}
	
}
