/**
 * generated by Xtext
 */
package org.iworkz.qon.ui.contentassist;

import org.iworkz.qon.ui.contentassist.AbstractQonDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class QonDslProposalProvider extends AbstractQonDslProposalProvider {
}
