/*
 * generated by Xtext
 */
package org.iworkz.qon.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractQonDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.iworkz.qon.qonDsl.QonDslPackage.eINSTANCE);
		return result;
	}
}
