/*
 * generated by Xtext
 */
package org.iworkz.qon;

import org.iworkz.qon.naming.QonQualifiedNameProvider;
import org.iworkz.qon.scoping.QonNamespaceAwareLocalScopeProvider;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QonDslRuntimeModule extends org.iworkz.qon.AbstractQonDslRuntimeModule {
	
    public void configureIScopeProviderDelegate(com.google.inject.Binder binder) {
        binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class)
                .annotatedWith(
                        com.google.inject.name.Names
                                .named("org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.delegate"))
                .to(QonNamespaceAwareLocalScopeProvider.class);
    }
	
	
    public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
        return QonQualifiedNameProvider.class;
    }


}
