/*
 * generated by Xtext
 */
package org.iworkz.qon;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class QonDslStandaloneSetup extends QonDslStandaloneSetupGenerated{

	public static void doSetup() {
		new QonDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

