/*
 * generated by Xtext
 */
package org.iworkz.qon.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.iworkz.qon.ui.highlighting.QonDslHighlightingConfiguration;
import org.iworkz.qon.ui.highlighting.QonDslSemanticHighlightingCalculator;


/**
 * Use this class to register components to be used within the IDE.
 */
public class QonDslUiModule extends org.iworkz.qon.ui.AbstractQonDslUiModule {
	public QonDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return QonDslHighlightingConfiguration.class;
	}

	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return QonDslSemanticHighlightingCalculator.class;
	}
}
