/*
 * generated by Xtext
 */
package org.iworkz.qon.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.iworkz.qon.services.QonDslGrammarAccess;

public class QonDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private QonDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.iworkz.qon.parser.antlr.internal.InternalQonDslParser createParser(XtextTokenStream stream) {
		return new org.iworkz.qon.parser.antlr.internal.InternalQonDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "QRoot";
	}
	
	public QonDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QonDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
