/*
 * generated by Xtext
 */
package org.iworkz.qon.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.iworkz.qon.services.QonDslGrammarAccess;

public class QonDslParser extends AbstractContentAssistParser {
	
	@Inject
	private QonDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.iworkz.qon.ui.contentassist.antlr.internal.InternalQonDslParser createParser() {
		org.iworkz.qon.ui.contentassist.antlr.internal.InternalQonDslParser result = new org.iworkz.qon.ui.contentassist.antlr.internal.InternalQonDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getQSystemPropertyAccess().getAlternatives(), "rule__QSystemProperty__Alternatives");
					put(grammarAccess.getQPropertyAccess().getAlternatives(), "rule__QProperty__Alternatives");
					put(grammarAccess.getQLinkPropertyAccess().getAlternatives(), "rule__QLinkProperty__Alternatives");
					put(grammarAccess.getQValuePropertyAccess().getAlternatives(), "rule__QValueProperty__Alternatives");
					put(grammarAccess.getBooleanValueAccess().getAlternatives(), "rule__BooleanValue__Alternatives");
					put(grammarAccess.getNumberAccess().getAlternatives_3_0(), "rule__Number__Alternatives_3_0");
					put(grammarAccess.getNumberAccess().getAlternatives_3_1(), "rule__Number__Alternatives_3_1");
					put(grammarAccess.getQRootAccess().getGroup(), "rule__QRoot__Group__0");
					put(grammarAccess.getQObjectAccess().getGroup(), "rule__QObject__Group__0");
					put(grammarAccess.getNamespacePropertyAccess().getGroup(), "rule__NamespaceProperty__Group__0");
					put(grammarAccess.getSchemaPropertyAccess().getGroup(), "rule__SchemaProperty__Group__0");
					put(grammarAccess.getImportPropertyAccess().getGroup(), "rule__ImportProperty__Group__0");
					put(grammarAccess.getImportPropertyAccess().getGroup_4(), "rule__ImportProperty__Group_4__0");
					put(grammarAccess.getImportPropertyAccess().getGroup_4_1(), "rule__ImportProperty__Group_4_1__0");
					put(grammarAccess.getQLinkObjectPropertyAccess().getGroup(), "rule__QLinkObjectProperty__Group__0");
					put(grammarAccess.getQLinkArrayPropertyAccess().getGroup(), "rule__QLinkArrayProperty__Group__0");
					put(grammarAccess.getQLinkArrayPropertyAccess().getGroup_4(), "rule__QLinkArrayProperty__Group_4__0");
					put(grammarAccess.getQLinkArrayPropertyAccess().getGroup_4_1(), "rule__QLinkArrayProperty__Group_4_1__0");
					put(grammarAccess.getQObjectPropertyAccess().getGroup(), "rule__QObjectProperty__Group__0");
					put(grammarAccess.getQStringValuePropertyAccess().getGroup(), "rule__QStringValueProperty__Group__0");
					put(grammarAccess.getQNumberValuePropertyAccess().getGroup(), "rule__QNumberValueProperty__Group__0");
					put(grammarAccess.getQBooleanValuePropertyAccess().getGroup(), "rule__QBooleanValueProperty__Group__0");
					put(grammarAccess.getQNullValuePropertyAccess().getGroup(), "rule__QNullValueProperty__Group__0");
					put(grammarAccess.getQObjectArrayPropertyAccess().getGroup(), "rule__QObjectArrayProperty__Group__0");
					put(grammarAccess.getQObjectArrayPropertyAccess().getGroup_4(), "rule__QObjectArrayProperty__Group_4__0");
					put(grammarAccess.getQStringArrayPropertyAccess().getGroup(), "rule__QStringArrayProperty__Group__0");
					put(grammarAccess.getQStringArrayPropertyAccess().getGroup_4(), "rule__QStringArrayProperty__Group_4__0");
					put(grammarAccess.getQNumberArrayPropertyAccess().getGroup(), "rule__QNumberArrayProperty__Group__0");
					put(grammarAccess.getQNumberArrayPropertyAccess().getGroup_4(), "rule__QNumberArrayProperty__Group_4__0");
					put(grammarAccess.getQEmptyArrayPropertyAccess().getGroup(), "rule__QEmptyArrayProperty__Group__0");
					put(grammarAccess.getNumberAccess().getGroup(), "rule__Number__Group__0");
					put(grammarAccess.getNumberAccess().getGroup_2(), "rule__Number__Group_2__0");
					put(grammarAccess.getNumberAccess().getGroup_3(), "rule__Number__Group_3__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getQualifiedNameWithWildCardAccess().getGroup(), "rule__QualifiedNameWithWildCard__Group__0");
					put(grammarAccess.getQRootAccess().getTypeAssignment_1(), "rule__QRoot__TypeAssignment_1");
					put(grammarAccess.getQRootAccess().getSystemPropertiesAssignment_3(), "rule__QRoot__SystemPropertiesAssignment_3");
					put(grammarAccess.getQRootAccess().getPropertiesAssignment_4(), "rule__QRoot__PropertiesAssignment_4");
					put(grammarAccess.getQObjectAccess().getTypeAssignment_1(), "rule__QObject__TypeAssignment_1");
					put(grammarAccess.getQObjectAccess().getPropertiesAssignment_3(), "rule__QObject__PropertiesAssignment_3");
					put(grammarAccess.getNamespacePropertyAccess().getValueAssignment_2(), "rule__NamespaceProperty__ValueAssignment_2");
					put(grammarAccess.getSchemaPropertyAccess().getLinkAssignment_3(), "rule__SchemaProperty__LinkAssignment_3");
					put(grammarAccess.getImportPropertyAccess().getValuesAssignment_4_0(), "rule__ImportProperty__ValuesAssignment_4_0");
					put(grammarAccess.getImportPropertyAccess().getValuesAssignment_4_1_1(), "rule__ImportProperty__ValuesAssignment_4_1_1");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment(), "rule__Import__ImportedNamespaceAssignment");
					put(grammarAccess.getQLinkObjectPropertyAccess().getPropertyNameAssignment_0(), "rule__QLinkObjectProperty__PropertyNameAssignment_0");
					put(grammarAccess.getQLinkObjectPropertyAccess().getLinkAssignment_3(), "rule__QLinkObjectProperty__LinkAssignment_3");
					put(grammarAccess.getQLinkArrayPropertyAccess().getPropertyNameAssignment_0(), "rule__QLinkArrayProperty__PropertyNameAssignment_0");
					put(grammarAccess.getQLinkArrayPropertyAccess().getLinksAssignment_4_0(), "rule__QLinkArrayProperty__LinksAssignment_4_0");
					put(grammarAccess.getQLinkArrayPropertyAccess().getLinksAssignment_4_1_1(), "rule__QLinkArrayProperty__LinksAssignment_4_1_1");
					put(grammarAccess.getQObjectPropertyAccess().getPropertyNameAssignment_0(), "rule__QObjectProperty__PropertyNameAssignment_0");
					put(grammarAccess.getQObjectPropertyAccess().getValueAssignment_2(), "rule__QObjectProperty__ValueAssignment_2");
					put(grammarAccess.getQStringValuePropertyAccess().getPropertyNameAssignment_0(), "rule__QStringValueProperty__PropertyNameAssignment_0");
					put(grammarAccess.getQStringValuePropertyAccess().getValueAssignment_2(), "rule__QStringValueProperty__ValueAssignment_2");
					put(grammarAccess.getQNumberValuePropertyAccess().getPropertyNameAssignment_0(), "rule__QNumberValueProperty__PropertyNameAssignment_0");
					put(grammarAccess.getQNumberValuePropertyAccess().getValueAssignment_2(), "rule__QNumberValueProperty__ValueAssignment_2");
					put(grammarAccess.getQBooleanValuePropertyAccess().getPropertyNameAssignment_0(), "rule__QBooleanValueProperty__PropertyNameAssignment_0");
					put(grammarAccess.getQBooleanValuePropertyAccess().getValueAssignment_2(), "rule__QBooleanValueProperty__ValueAssignment_2");
					put(grammarAccess.getQNullValuePropertyAccess().getPropertyNameAssignment_0(), "rule__QNullValueProperty__PropertyNameAssignment_0");
					put(grammarAccess.getQObjectArrayPropertyAccess().getPropertyNameAssignment_0(), "rule__QObjectArrayProperty__PropertyNameAssignment_0");
					put(grammarAccess.getQObjectArrayPropertyAccess().getValuesAssignment_3(), "rule__QObjectArrayProperty__ValuesAssignment_3");
					put(grammarAccess.getQObjectArrayPropertyAccess().getValuesAssignment_4_1(), "rule__QObjectArrayProperty__ValuesAssignment_4_1");
					put(grammarAccess.getQStringArrayPropertyAccess().getPropertyNameAssignment_0(), "rule__QStringArrayProperty__PropertyNameAssignment_0");
					put(grammarAccess.getQStringArrayPropertyAccess().getValuesAssignment_3(), "rule__QStringArrayProperty__ValuesAssignment_3");
					put(grammarAccess.getQStringArrayPropertyAccess().getValuesAssignment_4_1(), "rule__QStringArrayProperty__ValuesAssignment_4_1");
					put(grammarAccess.getQNumberArrayPropertyAccess().getPropertyNameAssignment_0(), "rule__QNumberArrayProperty__PropertyNameAssignment_0");
					put(grammarAccess.getQNumberArrayPropertyAccess().getValuesAssignment_3(), "rule__QNumberArrayProperty__ValuesAssignment_3");
					put(grammarAccess.getQNumberArrayPropertyAccess().getValuesAssignment_4_1(), "rule__QNumberArrayProperty__ValuesAssignment_4_1");
					put(grammarAccess.getQEmptyArrayPropertyAccess().getPropertyNameAssignment_0(), "rule__QEmptyArrayProperty__PropertyNameAssignment_0");
					put(grammarAccess.getBooleanValueAccess().getTrueAssignment_0(), "rule__BooleanValue__TrueAssignment_0");
					put(grammarAccess.getBooleanValueAccess().getFalseAssignment_1(), "rule__BooleanValue__FalseAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.iworkz.qon.ui.contentassist.antlr.internal.InternalQonDslParser typedParser = (org.iworkz.qon.ui.contentassist.antlr.internal.InternalQonDslParser) parser;
			typedParser.entryRuleQRoot();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public QonDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QonDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
