/*
 * generated by Xtext
 */
package org.iworkz.qon.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.iworkz.qon.ui.internal.QonDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QonDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return QonDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return QonDslActivator.getInstance().getInjector(QonDslActivator.ORG_IWORKZ_QON_QONDSL);
	}
	
}
